package config

const DEBUG=false

const DEFAULT_FILENAME = "go.mod"

const EDITOR_BOX_TOP = 2
const EDITOR_BOX_LEFT = 2
const EDITOR_BOX_WIDTH = 50
const EDITOR_BOX_HEIGHT = 10

const STATUS_BOX_TOP = EDITOR_BOX_TOP + EDITOR_BOX_HEIGHT + 1
const STATUS_BOX_LEFT = EDITOR_BOX_LEFT
const STATUS_BOX_WIDTH = EDITOR_BOX_WIDTH
const STATUS_BOX_HEIGHT = 3

const MAX_DISPLAY_LINES = EDITOR_BOX_HEIGHT - 2
const MAX_DISPLAY_COLS = EDITOR_BOX_WIDTH - 2
